# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.box = "ubuntu/xenial64"
   config.vm.synced_folder "../.", "/home/ubuntu/code"
   config.ssh.forward_x11 = true
   config.vm.network "forwarded_port", guest: 8000, host: 8000, auto_correct: true
   config.vm.network "forwarded_port", guest: 25, host: 2525, auto_correct: true
   config.vm.network "private_network", ip: "192.168.10.10"
   config.vm.provider :virtualbox do |virtualbox|
      virtualbox.customize ["modifyvm", :id, "--name", "Maalbox"]
      virtualbox.customize ["modifyvm", :id, "--memory", "1024"]
  end
   config.vm.provision :shell, :inline => $startup
end

$startup = <<EOF
   #basic tools
   sudo apt-get update
   sudo apt-get -y install build-essential # g++, make, etc.
   sudo apt-get -y install git
   sudo apt-get -y install curl
   sudo apt-get -y install x11-apps

   #python3 and headers
   sudo apt-get -y install python3
   sudo apt-get -y install python3-dev

   sudo mkdir -p /data/db

   #download some example notebooks
   # git clone https://github.com/kyledinh/maalbox.git
   sudo apt-get -y install python3-pip
   sudo apt-get -y install mongodb
   sudo pip3 install Flask
   sudo pip3 install pymongo
   sudo pip3 install selenium

   # run the servers: database and webserver
   # sudo ~/maalbox/python/bin/start_mongo.sh > ~/mongo.log 2>&1 &
   # sudo ~/maalbox/python/maalserver.py > ~/maalserver.log 2>&1 &
EOF
